---
title: "Predicting Housing Prices in Ames, Iowa"
author: "Blake Cizek"
date: "December 2017"
output:
  html_document: default
  word_document: default
  pdf_document: default
---
##Overview
Housing - humanity's simple, yet complex and timeless paradigm. Families & individuals, buyers & sellers, and businesses & investors all continually try to crack the code - finding the right housing price to balance one's life and future. Predicting housing prices is an invaluable, yet frustrating endeavor. 

For my Foundations of Data Science Capstone Project, the goal is to predict housing prices in Ames, Iowa - based on Kaggle's Advanced Regression Techniques Competition. While this competition is no longer active, its scope and data present itself to be a choice starting ground for testing data cleaning, exploratory data analysis, statistics and machine learning skills.

##Scope
The recipient of this Capstone Project would ideally be Zillow. As a technology leader in the real estate industry, Zillow continually looks for analyses and algorithms to improve its platform, which serves both the buyer and seller of residential properties. Although Zillow already owns and maintains a vast array of data science assets, they are continually looking for opportunities to improve their process and bottom line. As an example of drive for excellence, Zillow is about to award a $1.2 million prize to a Kaggle team which will help them whittle down their Zestimate's 5% prediction error rate.  

##Data
Following the guidelines of Kaggle's Advanced Regression Techniques Competition, the majority of the [data](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data) used in this project will be sourced from Dean De Cock's educational study. As a part of the exploratory analysis phase, other complementary datasets from the U.S. Census, Quandl, Redfin and Zillow may be used to supplement macro-economic data or any other specific insight. 

The primary dataset from the Kaggle Competition consists of a training set and a test set. Present in each set are 79 predictor variables (house attributes) and one target variable (price). Of these 79, 51 are categorical and 28 are continuous. Each predictor variable could be categorized in the following manner:

* lot/land variables  

* location variables  

* age variables  

* appearance variables  

* external features (pools, porches, etc.) variables  

* room/bathroom variables  

* kitchen variables  

* basement variables  

* roof variables  

* garage variables  

* utilities variables  

##Project Workflow:
*Section 1: Data Assessment*

* Approach to Problem  

* Exploratory Data Analysis  

* Understanding the Data  

*Section 2: Model prepartation*

* Feature Selection  

* Feature Engineering   

* Data Cleaning  

*Section 3: Model Fitting*

* Model Selection  

    - Multiple linear regression  

    - Ridge regression  

    - Elastic net regression  

    - Spline regression  

    - LASSO  

    - Arena Model
  
* Model Fitting  

* Parameters Tuning 

##Deliverables
The goal of this project is to accurately predict residential real estate prices as accurately as possible given the flux nature of the housing market and macroeconomic factors at large. To accomplish this the primary deliverable will be the model and algorithm that will be developed and/or fine-tuned to reduce error and predict prices accurately. 

To share these findings, code and a paper will be published at the conclusion of this capstone project. 


